// Generated by CoffeeScript 1.10.0
(function() {
  var AppRegistry, React, StyleSheet, Text, View, _, _Text, _View, a, body, c, circle, clipPath, code, d, defs, div, ellipse, feBlend, feGaussianBlur, feMerge, feMergeNode, feOffset, filter, foreignObject, g, h1, h2, h3, h4, h5, h6, image, input, li, line, linearGradient, ol, p, path, pattern, polygon, polyline, radialGradient, rect, ref, ref1, ref2, rr, rr_0, span, stop, svg, text, textArea, ul;

  ref = require('./boilerplate')(), _ = ref._, c = ref.c, React = ref.React, rr = ref.rr, rr_0 = ref.rr_0;

  ref1 = React.DOM, p = ref1.p, div = ref1.div, h1 = ref1.h1, h2 = ref1.h2, h3 = ref1.h3, h4 = ref1.h4, h5 = ref1.h5, h6 = ref1.h6, span = ref1.span, svg = ref1.svg, circle = ref1.circle, rect = ref1.rect, ul = ref1.ul, line = ref1.line, li = ref1.li, ol = ref1.ol, code = ref1.code, a = ref1.a, input = ref1.input, defs = ref1.defs, clipPath = ref1.clipPath, body = ref1.body, linearGradient = ref1.linearGradient, stop = ref1.stop, g = ref1.g, path = ref1.path, d = ref1.d, polygon = ref1.polygon, image = ref1.image, pattern = ref1.pattern, filter = ref1.filter, feBlend = ref1.feBlend, feOffset = ref1.feOffset, polyline = ref1.polyline, feGaussianBlur = ref1.feGaussianBlur, feMergeNode = ref1.feMergeNode, feMerge = ref1.feMerge, radialGradient = ref1.radialGradient, foreignObject = ref1.foreignObject, text = ref1.text, textArea = ref1.textArea, ellipse = ref1.ellipse, pattern = ref1.pattern;

  ref2 = require('react-native'), AppRegistry = ref2.AppRegistry, StyleSheet = ref2.StyleSheet, Text = ref2.Text, View = ref2.View;

  _View = React.createFactory(View);

  _Text = React.createFactory(Text);

  module.exports = function() {
    return rr_0({
      render: function() {
        return _View(null, _Text(null, "HELLLLLLLLLLLLLLLOOOOOOOOOOOOOO"));
      }
    });
  };

}).call(this);
